GET localhost:8081/hello
Authorization: Bearer 12298fdncsdaj

###
POST localhost:8081/auth/register

{
    "email": "coco@co.co",
    "password": "coco12",
    "name": "coco_sh"
}

###
POST localhost:8081/link

{
    "url": "https://mail.ru"
}

###
GET localhost:8081/teeewr

###
PATCH localhost:8081/link/3

{
    "url": "https://google.com",
    "hash": "goo.gl"
}

###
DELETE localhost:8081/link/4