GET localhost:8081/hello
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvY29AY28uY28ifQ.Tdj_6Ip7oLI2Wo0SPzqhwWcbP8XnFNX_ubWDpfWHaHM

###
POST localhost:8081/auth/register

{
    "email": "coco@co.co",
    "password": "coco12",
    "name": "coco_sh"
}

###
POST localhost:8081/auth/login

{
    "email": "coco@co.co",
    "password": "coco12"
}


###
POST localhost:8081/link

{
    "url": "https://mail.ru"
}

###
GET localhost:8081/goo.gl

###
PATCH localhost:8081/link/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvY29AY28uY28ifQ.Tdj_6Ip7oLI2Wo0SPzqhwWcbP8XnFNX_ubWDpfWHaHM

{
    "url": "https://google.com",
    "hash": "goo.gl"
}

###
DELETE localhost:8081/link/4

### Get links
GET localhost:8081/link?limit=2&offset=0