GET localhost:8081/hello

###
POST localhost:8081/auth/login

{
    "email": "coco@co.co",
    "password": "123"
}

###
POST localhost:8081/link

{
    "url": "https:/"
}

###
DELETE localhost:8081/link/1