version: '3.7'
services:
  postgres:
    container_name: postgres_go
    image: postgres:16.4-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - ./postgres-data:/data/postgres
    ports:
      - ${DB_PORT}:5432